# Generated by Django 4.2.1 on 2023-07-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mynews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstitle', models.CharField(max_length=255)),
                ('newsdescription', models.TextField()),
            ],
            options={
                'db_table': 'itsnews',
            },
        ),
    ]
